# Problem 2
"""Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms."""

if __name__ == "__main__":
    a = 1
    b = 2
    even_sum = 2

    while True:
        new_term = a + b
        if new_term > 4000000:
            break
        a, b = b, new_term

        if not (b & 1):
            # True if last bit is 0 (number is even)
            even_sum += b

    print(even_sum)
